TM09-15 - Сверстать страницу регистрации
Team-09-practicum/Traffic-Racer pull request #12
Opened 2022-11-30 11:20 UTC by LarryBezrukov

### Какую задачу решаем

Добавлено:

Страница регистрации;
Базовые стили для RegistrationPage;

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-11-30 12:25 UTC, StepanovaValeriya approved these changes
Принято

2022-11-30 15:09 UTC, Rufflet requested changes
Привет. Коммит с версткой страницы авторизации здесь явно лишний. Убери, пожалуйста эти файлы (как конкретно сделать не подскажу, но возможно тебе поможет ответ на [SO](https://stackoverflow.com/a/51400593/5260115))

Также в этой задаче требовалось добавить ещё и валидацию. Но так как компонент валидации еще в разработке, предлагаю добавить этот момент как подзадачу, чтобы не забыть.

2022-11-30 15:09 UTC, Rufflet commented on packages/client/src/pages/authPage/AuthPage.scss
> +.auth {
Данный PR содержит коммит 3a1ee4327cef6c530f3fec8ae5f9fff8cd218eb6, который не относится к задаче этого PR. Авторизация у тебя идет в другом PR (#11). Необходимо исключить файлы/коммит.

2022-11-30 15:09 UTC, Rufflet commented on packages/client/src/pages/authPage/AuthPage.tsx
> +  <Row justify="center" align="middle" className="auth">
Аналогично предыдущему замечанию - этот файл у тебя в другом PR. К тому же не хватает ссылки "Нет аккаунта"
![warn](https://user-images.githubusercontent.com/15361093/204832975-af38de59-977c-4df9-ab91-46a9bb37d414.gif)

2022-11-30 20:10 UTC, LarryBezrukov commented on packages/client/src/pages/authPage/AuthPage.scss
> +.auth {
Исправил.

2022-11-30 21:05 UTC, Rufflet approved these changes
Принял

2022-12-01 11:36 UTC, arudenko-offcl approved these changes
👌 
Но поправь копипасту name в полях. И в остальных Пр проверь

2022-12-01 11:36 UTC, arudenko-offcl commented on packages/client/src/pages/registrationPage/RegistrationPage.tsx
> +            { required: true, message: 'Пожалуйста, введите ваше имя!' },
Понимаю, что это не финальное состояние макета, но подумай о том, что бы вынести правила проверок из верстки

2022-12-01 11:36 UTC, arudenko-offcl commented on packages/client/src/pages/registrationPage/RegistrationPage.tsx
> +          name="login"
копипаста )

2022-12-01 12:42 UTC, merged