TM09-28, TM09-29 screen of start and end game
Team-09-practicum/Traffic-Racer pull request #15
Opened 2022-12-03 12:42 UTC by Al-nvrsk

### Какую задачу решаем
Добавлено:
 - экран начала игры
 - экран завершения игры

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-12-03 13:31 UTC, LarryBezrukov approved these changes
В остальном замечание нет.

2022-12-03 13:31 UTC, LarryBezrukov commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +    pointer-events: all;
`pointer-events: none` и `pointer-events: all` противоречат друг другу.

2022-12-03 13:31 UTC, LarryBezrukov commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +    pointer-events: all
Тут то же самое

2022-12-03 14:52 UTC, swash1 reviewed
Не оч понял почему endGame и startGame находятся в utils, это же компоненты

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +      }
полетела скобка

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +    100% { color: rgb(255, 255, 255); }
цвета лучше в константы уносить, чтобы в проекте не размазываться по всей палитре
и брать их оттуда в дальнейшем

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.tsx
> +    <h1 className="gameOverPage__text">Игра окончена</h1>
В antd есть компонент `Typography`, в котором можно задать заголовки
Вроде в последний созвон договорились использовать его

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.tsx
> +  <div className="gameOverPage">
классы обычно именуются через snake-case: `game-over-page`

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.tsx
> +interface GameEndProps {
Можно просто `Props`

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +    background-color: rgba(0,0,0,0.4);
тоже в константы бы, и в константах лучше не задавать прозрачность, а использовать `opacity` по месту использования

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +    opacity: 1;
Два раза `opacity` - не оч понял)

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +    }
скобка полетела

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +        margin: 15px auto;
давай 16px? договорились в телеге использовать абсолютные значения в стилях кратные 4

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +    }
скобка полетела тоже)

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.tsx
> +      <h3 className="modalWindow__blink__text__instr">
По БЭМ так нельзя, лучше `modal-window__instructions` и `modal-window__start`
Не очень понимаю зачем оставлять в классе элемент `blink`

Мне кажется тут должна быть другая структура, что-то такое:
```
.modal-window_blink  // т.к. blink, кажется, модификатор - говорит что элемент должен моргать
  .modal-window__instructions
  .modal-window__start
```

Плюс тоже заюзать компонент типографии из antd

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +    animation: ani 1s forwards;
Имя `ani` у анимации не говорит что в ней происходит) хотя там просто изменение прозрачности
Почему бы не `makeVisible`?)

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.tsx
> +export default GameStart;
Лучше избегать дефолтных экспортов - когда пишешь код, ide проще подхватывать именованные экспорты

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/GamePage.tsx
> +      {isGameOver && <GameEnd score={score} />}
Тут странная тема получается что будто бы можем получать сразу несколько состояний, но по идее они не сочетаются, возможно стоит вынести в отдельную функцию и по ифакам возвращать только одно состояние

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +      }
Внутри `.link {
}`
можно писать
`&:hover {
}`

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.tsx
> +    <div className="blink"> Для повтора нажмите любую клавишу </div>
может `game-over-page__repeat-message`?

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +    font-weight: bold;
Компонент `Typography` может настраивать толщину, или принимать `className`, через который это можно задать

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/GamePage.tsx
> +      {isGameOver && <GameEnd score={score} />}
`isGameOver` -> `shouldShowEndScreen`

2022-12-03 14:52 UTC, swash1 commented on packages/client/src/pages/gamePage/GamePage.tsx
> +      {isFirstStart && <GameStart />}
`isFirstStart` -> `shouldShowStartScreen`

2022-12-03 15:28 UTC, Rufflet requested changes
Нужно привести компоненты к единообразию по структуре разметки, стилей и неймингу. Оставил комментарии ниже

2022-12-03 15:28 UTC, Rufflet commented on packages/client/src/pages/gamePage/GamePage.tsx
> +import GameStart from './utils/startGame/GameStart';
На мой взгляд страницы-компоненты начала и завершения игры лучше перенести в папку components внутри gamePage

2022-12-03 15:28 UTC, Rufflet commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +.modalWindow {
почему `.modalWindow` а не `.gameStartPage`? Здесь можно и нужно сохранить единообразие с компонентом GameEnd

2022-12-03 15:28 UTC, Rufflet commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +    pointer-events: all
строки 11-15 здесь лишние, т.к. ты не управляешь свойством opacity, ведь экран старта игры открыт сразу же (и без анимации появления) при попадании на роут с игрой

2022-12-03 15:28 UTC, Rufflet commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +@keyframes modalWindow__blink {
это лучше привести к виду как в стилях GameEnd.scss
- чтобы ".blink" отвечал только за анимированную смену цвета.
- классы `__text` и `__text__instr` сделать потомками основного класса ~~`modalWindow`~~ `gameStartPage`

Это улучшит читаемость и уменьшит уровень вложенности, в т.ч. в самом компоненте GameStart.tsx

2022-12-03 15:28 UTC, Rufflet commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.tsx
> +  </div>
После правки стилей эти строки нужно немного отрефакторить. Должно получиться примерно так как на скриншоте
![image](https://user-images.githubusercontent.com/15361093/205448226-d6bc1d29-270c-46b6-9f4a-262fa10ec044.png)

2022-12-03 15:28 UTC, Rufflet commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +    pointer-events: all;
Кроме 16 строки (`animation: ani 1s forwards;`) остальное это лишние правила, т.к. видимостью управляет `ani` и у него свой transition

2022-12-03 15:28 UTC, Rufflet commented on packages/client/src/pages/gamePage/GamePage.tsx
> +import GameStart from './utils/startGame/GameStart';
Для сохранения единообразия в нейминге, стоит называть папку с компонентом также, как и файл компонента (сейчас в папке endGame лежит GameEnd.tsx)

2022-12-03 15:53 UTC, Rufflet commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.tsx
> +  <div className="gameOverPage">
> классы обычно именуются через snake-case: `game-over-page`

может ли такое проверять линтер (eslint или stylelint)? если да - надо подключить

2022-12-03 16:40 UTC, swash1 commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.tsx
> +  <div className="gameOverPage">
Посмотрю, но кажется вряд ли

2022-12-05 06:56 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +    pointer-events: all;
Исправил

2022-12-05 06:56 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +    pointer-events: all
Исправил

2022-12-05 06:57 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +      }
Исправил

2022-12-05 06:57 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +    100% { color: rgb(255, 255, 255); }
Исправил

2022-12-05 06:57 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.tsx
> +    <h1 className="gameOverPage__text">Игра окончена</h1>
Исправил

2022-12-05 06:57 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.tsx
> +  <div className="gameOverPage">
Исправил

2022-12-05 06:58 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.tsx
> +interface GameEndProps {
Исправил в соответствии с договоренностями в команде

2022-12-05 07:11 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +    background-color: rgba(0,0,0,0.4);
Цвет фона вынес в константы. Как понимаю, в предложенном варианте `opacity` тогда тоже надо будет выносить в отдельную константу для возможности гибкой настройки. Также потребуется дополнительный класс  для обхода побочного эффекта с дочерним текстом, который не перетирается. В данном случае считаю, что для простоты кода прозрачность лучше использовать сразу в цвете.

2022-12-05 07:11 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +    opacity: 1;
Исправил

2022-12-05 07:11 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +    }
Исправил

2022-12-05 07:11 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +        margin: 15px auto;
Исправил

2022-12-05 07:11 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +    }
Исправил

2022-12-05 07:12 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.tsx
> +      <h3 className="modalWindow__blink__text__instr">
Исправил

2022-12-05 07:12 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +    animation: ani 1s forwards;
Исправил

2022-12-05 07:12 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.tsx
> +export default GameStart;
Исправил

2022-12-05 07:31 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/GamePage.tsx
> +      {isGameOver && <GameEnd score={score} />}
При реализации дополнительной функции проверки, считаю необходимо будет сразу продумывать про механизм обработки возможной ошибки (сразу ошибку выкидывать или дополнительный экран создавать). При необходимости думаю лучше реализовывать в отдельной задаче.

2022-12-05 07:31 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.tsx
> +    <div className="blink"> Для повтора нажмите любую клавишу </div>
Исправил

2022-12-05 07:33 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +    font-weight: bold;
Исправил. Использовал однотипно со страницей начала игры компонент `Typography.Title`

2022-12-05 07:38 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/GamePage.tsx
> +      {isGameOver && <GameEnd score={score} />}
При отсутствии дополнительной логики для окончания игры, считаю использование условного рендеринга сразу на основании `state` достаточным

2022-12-05 07:39 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/GamePage.tsx
> +      {isFirstStart && <GameStart />}
При отсутствии дополнительной логики для начала игры, считаю использование условного рендеринга сразу на основании state достаточным

2022-12-05 07:39 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/GamePage.tsx
> +import GameStart from './utils/startGame/GameStart';
Исправил

2022-12-05 07:39 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +.modalWindow {
Исправил

2022-12-05 07:39 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +    pointer-events: all
Исправил

2022-12-05 07:40 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +@keyframes modalWindow__blink {
Исправил

2022-12-05 07:40 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.tsx
> +  </div>
Исправил

2022-12-05 07:40 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/endGame/GameEnd.scss
> +    pointer-events: all;
Исправил

2022-12-05 10:09 UTC, Rufflet commented on packages/client/src/pages/gamePage/utils/startGame/GameStart.scss
> +    background-color: rgba(0,0,0,0.4);
Я думаю, Тимур предлагал реализовать как `background-color: rgba($background-color, 0.5);`, т.е. цвет из константы, а значение `opacity` по месту, т.е. в правиле `rgba`

2022-12-05 10:11 UTC, Rufflet approved these changes

2022-12-05 11:17 UTC, swash1 commented on packages/client/src/pages/gamePage/GamePage.tsx
> +      {isGameOver && <GameEnd score={score} />}
оке

2022-12-05 12:45 UTC, arudenko-offcl approved these changes
👌

2022-12-05 15:23 UTC, swash1 approved these changes

2022-12-05 15:23 UTC, swash1 commented on packages/client/src/pages/gamePage/components/startGame/GameStart.tsx
> +    <Title className="game-start__text__blink" level={3}>
`blink` это модификатор получается, правильнее будет `game-start__text game-start__text_blink`
https://ru.bem.info/methodology/faq/#почему-не-стоит-создавать-элементы-элементов-block__elem1__elem2

2022-12-05 15:23 UTC, swash1 commented on packages/client/src/pages/gamePage/components/gameEnd/GameEnd.scss
> +    &.ant-typography {
не получится тут стилизовать только через класс, который ты прокинул в компонент? По идее он прокидывается как раз для этого

2022-12-05 15:23 UTC, swash1 commented on packages/client/src/pages/gamePage/components/gameEnd/GameEnd.scss
> +      &.ant-typography {
и тут

2022-12-05 15:23 UTC, swash1 commented on packages/client/src/pages/gamePage/components/startGame/GameStart.scss
> +      &.ant-typography {
и тут

2022-12-05 15:23 UTC, swash1 commented on packages/client/src/styles/colors.scss
> +$text-color-start-end: $base;
здесь хранятся константы, которые могут быть использованы во всем проекте, а эта константа скорее всего будет использоваться только на странице с игрой, думаю стоит создать рядом со страницей файл `constants.scss`, где ее задать, и далее ее оттуда импорить в scss-файлы нужных компонентов страницы

2022-12-05 15:23 UTC, swash1 commented on packages/client/src/styles/colors.scss
> +$background-color: rgba(0, 0, 0, 0.53);
Не очень хочется хранить такие штуки, но штош
Давай тогда назовем ее `$black-transparent-50` и 0.53 -> 0.5, если не против

2022-12-05 16:43 UTC, merged