Tm09 98 добавить объектов на обочину
Team-09-practicum/Traffic-Racer pull request #47
Opened 2023-01-11 20:20 UTC by StepanovaValeriya

### Какую задачу решаем
Добавлены фонари, дорожные знаки и объекты на обочину.
Добавлен звук при наезде автомобиля на лужу.

В дальнейшем можно сделать разные темы оформления обочины. Например, трасса в городе. 

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-01-12 06:36 UTC, Al-nvrsk approved these changes
:+1:  Дополнительно предлагаю пофиксить возможность обрезать правую обочину, при уменьшении окна браузера. С левой отрабатывает отлично.

2023-01-12 06:36 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/utils/roadside/RoadObject.ts
> +
Т.к. объекты на обочине разные, предлагаю размер `width` и `height` брать из image, добавив ограничения на максимально допустимый

2023-01-12 06:36 UTC, Al-nvrsk commented on packages/client/src/pages/gamePage/components/TrafficRacer/TrafficRacer.tsx
> +      }
Предлагаю объединить условия `!isOver.current &&  isSoundOn.current`

2023-01-12 14:47 UTC, StepanovaValeriya commented on packages/client/src/pages/gamePage/components/TrafficRacer/TrafficRacer.tsx
> +      }
Исправила

2023-01-12 19:18 UTC, arudenko-offcl approved these changes
LGTM

2023-01-12 19:18 UTC, arudenko-offcl commented on packages/client/src/pages/gamePage/utils/Obstacle.ts
> +    return 580 + GameConfig.scenario.lanesSize * newRandom;
Напомни плиз, что это за магическое число и почему оно поменялось ?

2023-01-12 19:18 UTC, arudenko-offcl commented on packages/client/src/pages/gamePage/utils/Scenario.ts
> +    for (let i = 0; i < GameConfig.roadside.objects; i++) {
Почему тут и в `createLights()` итерируешься через `for () {}` ?

Мне кажется, что чуть нагляднее можно сделать с помощью метода массива map()

Тем более, вижу, что выше ты используешь методы массивов (`forEach()`).

Что думаешь ?

2023-01-12 19:18 UTC, arudenko-offcl commented on packages/client/src/pages/gamePage/utils/roadside/Light.ts
> +    return this.side === 0 ? 330 + newX : 820 + newX;
На мой взгляд, тут без тернарника читалось бы легче. 

А вот в конструкторе при задании `this.image.src` он был бы более читаем чем тут. Но это чисто мое субъективное мнение.

В каких случаях ты предпочитаешь использовать if/else, а когда тернарный оператор? Не воспринимай, как замечание, просто интересно)

2023-01-12 19:31 UTC, StepanovaValeriya commented on packages/client/src/pages/gamePage/utils/Obstacle.ts
> +    return 580 + GameConfig.scenario.lanesSize * newRandom;
Это расположение препятствий на дороге по оси X, нужно для того, чтобы препятствия располагались ровно по центру полосы. Значение изменилось, т.к. я изменила(увеличила) всю ширину элемента canvas, для того чтобы разместить дорожные объекты.

2023-01-12 19:40 UTC, StepanovaValeriya commented on packages/client/src/pages/gamePage/utils/Scenario.ts
> +    for (let i = 0; i < GameConfig.roadside.objects; i++) {
У нас во всех методах, которые создают какие-либо объекты используется for, поэтому и я сделала через for. Чтобы методы имели примерно одинаковую структуру.

2023-01-12 19:52 UTC, StepanovaValeriya commented on packages/client/src/pages/gamePage/utils/roadside/Light.ts
> +    return this.side === 0 ? 330 + newX : 820 + newX;
Я думаю, что здесь тернарный оператор не ухудшает читаемость кода, т.к. нет громоздких условий и  вложенностей. В большинстве случаев использую if, т.к. читается легче.

2023-01-12 19:56 UTC, Rufflet requested changes
Обрати внимание на размер ассетов. У тебя есть картинки весом более 4 мегабайт. Стоит изменить размеры картинок, сделать их существенно меньше и легче.

Также при изменений размеров учти пропорции. Например, сейчас колодец больше чем отель.

2023-01-12 19:56 UTC, Rufflet commented on packages/client/src/pages/gamePage/utils/roadside/Tree.ts
> -    const newX = Math.random() * this.width;
Я бы оставил небольшой разброс по координатам для деревьев. В один ряд они как-то слишком искусственно выглядят. на мой взгляд.

2023-01-12 20:00 UTC, Rufflet commented on packages/client/src/pages/gamePage/utils/Scenario.ts
> +import { RoadObject } from './roadside/RoadObject';
Когда будешь мёржить с dev веткой, сделай реэкспорт из `packages/client/src/pages/gamePage/utils/roadside/index.ts`

2023-01-13 18:25 UTC, StepanovaValeriya commented on packages/client/src/pages/gamePage/utils/roadside/RoadObject.ts
> +
Согласна. Исправила.

2023-01-14 09:38 UTC, StepanovaValeriya commented
- Пофиксила размеры и пропорции картинок. Ширина и высота теперь берется из image, но с проверкой на максимально допустимые значения. Пожалуйста посмотрите, может что-нибудь еще поменять нужно?
- Еще увеличила ширину обочины;
- Устранила конфликты слияния;
- У дорожного знака CityLimitSign изменила координаты x и y, т.к. изменилась ширина обочины.

2023-01-15 14:55 UTC, Rufflet approved these changes
Я не буду блокировать слияние, но вот несколько финальных комментариев от меня:
1) по поводу ширины игры и скролла я написал
2) остались большие картинки (tree5, tree6, roadSign1, roadSign2, lightLeft, lightRight)
3) может перенести содержимое папки `packages/client/src/pages/gamePage/utils/roadside/assets` в папку с ассетами игры `packages/client/src/pages/gamePage/assets`

2023-01-15 14:55 UTC, Rufflet commented on packages/client/src/pages/gamePage/utils/game.config.ts
> +    width: 1800,
Мне кажется это уже слишком много для игры.
Посмотри [статистику по разрешениям](https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide) экрана. FullHD только у 22% пользователей.

У меня 1600 в ширину на маке и теперь в игре появился горизонтальный скрол.

2023-01-20 15:00 UTC, StepanovaValeriya commented
В последнем коммите:
- Уменьшила размеры ассетов tree5, tree6, roadSign1, roadSign2, lightLeft, lightRight;
- Вернула ширину 1600;
- Перенесла содержимое папки packages/client/src/pages/gamePage/utils/roadside/assets в папку с ассетами игры packages/client/src/pages/gamePage/assets, +импорты изменила;
- Пофиксила расстояния между деревьями, объектами, чтобы не накладывались друг на друга.

2023-01-22 18:03 UTC, merged