Tm09 93 add redux tests
Team-09-practicum/Traffic-Racer pull request #56
Opened 2023-02-05 09:13 UTC by Al-nvrsk

### Какую задачу решаем
1. Добавлены и обновлены тесты на компоненты Redux
Дополнительно:
- Устранен warning в `App.test.tsx`
- Устранен warning в `router.test.tsx`
- Устранен warning на `useNavigate` и `useLayoutEffect` при `SSR`
- Убрано отдельное состояние `isAuth` в сторе . Параметр берется реселектом от `user`
- Селекторы заменены на `useAppSelector`
- Устранена ошибка в themeController на серверной части
- Добавлен дефолтый город, появляющийся при ошибке запроса геолокации

2023-02-05 16:16 UTC, Rufflet requested changes
👏🏻 Большая работа проделана

Оставил несколько замечаний по коду

2023-02-05 16:16 UTC, Rufflet commented on packages/client/src/App.test.tsx
> +  test('Example test', async () => {
Давай укажем здесь осмысленные названия теста

2023-02-05 16:16 UTC, Rufflet commented on packages/client/src/App.test.tsx
>  global.fetch = jest.fn(() => Promise.resolve({ json: () => Promise.resolve('hey') }));
Эти строки достались нам из темплейта проекта.
Но и без них все тесты успешно проходят, т.к. `fetch` в тестах не используется. Предлагаю убрать.

Тем более это единственное место в проекте, где используется `// @ts-ignore`

2023-02-05 16:16 UTC, Rufflet commented on packages/client/src/utils/store/selectors/getIsAuthSelector/getIsAuthSelector.test.ts
> +          id: 0,
Уверен на 99%, что в БД возможен вариант создания юзера с id=0. Так что иметь юзера с таким айди в сторе - это не негативный результат теста. 

Похоже у нас селектор `isAuth` не совсем верно написан: `export const getIsAuth = createSelector(getUserFull, (user) => !!user?.id);`. Стоит проверять кол-во или наличие определённых ключей. Того же id, например.

Как думаешь?

2023-02-05 16:16 UTC, Rufflet commented on packages/server/controllers/themeController.ts
> +      res.status(200).json('Ok');
В метод `json` нужно передавать объект, т.е. например `res.status(200).json({ status: 'OK' })`
Дефолтный статус 200 тоже не обязательно, но пусть будет для консистентности

2023-02-05 20:29 UTC, arudenko-offcl requested changes
Заметил, что ты не используешь [Queries API](https://testing-library.com/docs/queries/about) для доступа к элементам. Ты не знал о таком апи или по другой причине решил не использовать?

Так же testing-library в своем подходе рекомендует максимально приближаться к тому, как юзер использует приложение, ну и на совсем крайний случай использовать подход с data-testid. [Вот здесь](https://testing-library.com/docs/queries/bytestid) в сноске есть ссылка на статью, где максимально подробно стараются раскрыть смысл такого подхода.

В общем, я предлагаю не отходить от рекомендованного подхода даже для небольших тестов, вроде твоих, если на то нет явных причин.

2023-02-06 08:00 UTC, Al-nvrsk commented on packages/client/src/utils/store/selectors/getIsAuthSelector/getIsAuthSelector.test.ts
> +          id: 0,
1. id=0 в БД возможно, но при стандартном поведении автокомплита в БД счет начинается с 1. Использование 0 в id не рекомендуется  [Why is negative id or zero considered a bad practice when inserting a primary key in a database table?](https://stackoverflow.com/questions/8927761/why-is-negative-id-or-zero-considered-a-bad-practice)
2. тест на 0 проверял именно текущую реализацию селектора, по которому при `id=0` будет `false` 

В текущей реализации `isAuth` определяется по наличию значения в поле `user.id`.  т.к. объект `user` хранится в Redux и попадает туда только от сервера, то валидировать наличие дополнительных ключей считаю излишним.

2023-02-06 09:04 UTC, Rufflet approved these changes
👌

2023-02-07 19:51 UTC, arudenko-offcl approved these changes

2023-02-07 20:45 UTC, swash1 approved these changes
👍

2023-02-08 04:46 UTC, merged